apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      containers:
        - name: jobs
          image: activatestaff-jobs:latest
          ports:
            - containerPort: 8080
