apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
        - name: workers
          image: activatestaff-workers:latest
          ports:
            - containerPort: 8081
